### ISSUE TITLE
FR: Setup doxie and link to the answers.

### ISSUE THREAD

**Issue by hemanth** [stoeffel/awesome-ama-answers#2]
I feel it would be good to use `doxie` here and link to answer rather than the whole text, so that people who are interested in the answer will also see other comments to that answer.

As in #1

**Comment by stoeffel** [comment]
> link to answer rather than the whole text

yop, a link would be good. But I think it's nice to have the answer directly in place and only for very long answers like the one in your last PR as a link.

**Comment by stoeffel** [comment]
> I feel it would be good to use doxie here

I think doxie would be overkill here.

> link to answer rather than the whole text

changed my mind on that :smile:
