### ISSUE TITLE
add a TOC

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/awesome-ama-answers#7]
This list is growing and needs a TOC. If you have a good idea, your PR would be appreciated :smile:

**Comment by RichardLitt** [comment]
I'm not sure; a TOC seems a bit premature for this, unless we split the awesome answers into categories based on the type of answer?

**Comment by stoeffel** [comment]
Maybe you are right, it's bit premature. Splitting into categories sounds like a overkill at this point unless you can already come up with some good categories.

**Comment by RichardLitt** [comment]
I think it's good as it is. That you don't have a good idea of what a TOC would look like either makes me think this is bikeshedding. Also - the TOC for each item would almost be as long as each item. :D

**Comment by stoeffel** [comment]
:-) you are right. Thanks any way. I will close this for now.

**Comment by RichardLitt** [comment]
No problem. :)
